import { runScenarios } from '../../../../../dispatch';
import type { ContextRef } from '../../../../../../harness/browser/scenarios';

const box: ContextRef = { by: 'id', id: 'box' };

runScenarios('an+b selector parsing', 'normal', [
  {
    name: ':nth-child an+b selectors parse',
    // status: 'only',
    markup: `
      <div id="box"></div>
    `,
    cases: [
      { match: ':nth-child(1n+0)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-child(n+0)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-child(n)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-child(-n+0)', ref: box, expect: { ids: [] } },
      { match: ':nth-child(-n)', ref: box, expect: { ids: [] } },
      { match: ':nth-child(N)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-child(+n+3)', ref: box, expect: { ids: [] } },
      { match: ':nth-child( +n + 7 )', ref: box, expect: { ids: [] } },
      { match: ':nth-child(  N- 123)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-child(n- 10)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-child(-n\n- 1)', ref: box, expect: { ids: [] } },
      { match: ':nth-child( 23n\n\n+\n\n123 )', ref: box, expect: { ids: [] } },

      { match: ':nth-child(n- 1 2)', ref: box, expect: { throws: true } },
      { match: ':nth-child(n-b1)', ref: box, expect: { throws: true } },
      { match: ':nth-child(n-+1)', ref: box, expect: { throws: true } },
      { match: ':nth-child(n-1n)', ref: box, expect: { throws: true } },
      { match: ':nth-child(-n -b1)', ref: box, expect: { throws: true } },
      { match: ':nth-child(-1n- b1)', ref: box, expect: { throws: true } },
      { match: ':nth-child(-n-13b1)', ref: box, expect: { throws: true } },
      { match: ':nth-child(-n-+1)', ref: box, expect: { throws: true } },
      { match: ':nth-child(-n+n)', ref: box, expect: { throws: true } },
      { match: ':nth-child(+ 1n)', ref: box, expect: { throws: true } },
      { match: ':nth-child(  n +12 3)', ref: box, expect: { throws: true } },
      { match: ':nth-child(  12 n )', ref: box, expect: { throws: true } },
      { match: ':nth-child(+12n-0+1)', ref: box, expect: { throws: true } },
      { match: ':nth-child(+12N -- 1)', ref: box, expect: { throws: true } },
      { match: ':nth-child(+12 N )', ref: box, expect: { throws: true } },
      { match: ':nth-child(+ n + 7)', ref: box, expect: { throws: true } },
    ],
  },
  {
    name: ':nth-last-child an+b selectors parse',
    // status: 'only',
    markup: `
      <div id="box"></div>
    `,
    cases: [
      { match: ':nth-last-child(1n+0)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-child(n+0)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-child(n)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-child(-n+0)', ref: box, expect: { ids: [] } },
      { match: ':nth-last-child(-n)', ref: box, expect: { ids: [] } },
      { match: ':nth-last-child(N)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-child(+n+3)', ref: box, expect: { ids: [] } },
      { match: ':nth-last-child( +n + 7 )', ref: box, expect: { ids: [] } },
      { match: ':nth-last-child(  N- 123)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-child(n- 10)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-child(-n\n- 1)', ref: box, expect: { ids: [] } },
      { match: ':nth-last-child( 23n\n\n+\n\n123 )', ref: box, expect: { ids: [] } },

      { match: ':nth-last-child(n- 1 2)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(n-b1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(n-+1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(n-1n)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(-n -b1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(-1n- b1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(-n-13b1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(-n-+1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(-n+n)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(+ 1n)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(  n +12 3)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(  12 n )', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(+12n-0+1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(+12N -- 1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(+12 N )', ref: box, expect: { throws: true } },
      { match: ':nth-last-child(+ n + 7)', ref: box, expect: { throws: true } },
    ],
  },
  {
    name: ':nth-of-type an+b selectors parse',
    // status: 'only',
    markup: `
      <div id="box"></div>
    `,
    cases: [
      { match: ':nth-of-type(1n+0)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-of-type(n+0)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-of-type(n)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-of-type(-n+0)', ref: box, expect: { ids: [] } },
      { match: ':nth-of-type(-n)', ref: box, expect: { ids: [] } },
      { match: ':nth-of-type(N)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-of-type(+n+3)', ref: box, expect: { ids: [] } },
      { match: ':nth-of-type( +n + 7 )', ref: box, expect: { ids: [] } },
      { match: ':nth-of-type(  N- 123)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-of-type(n- 10)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-of-type(-n\n- 1)', ref: box, expect: { ids: [] } },
      { match: ':nth-of-type( 23n\n\n+\n\n123 )', ref: box, expect: { ids: [] } },

      { match: ':nth-of-type(n- 1 2)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(n-b1)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(n-+1)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(n-1n)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(-n -b1)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(-1n- b1)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(-n-13b1)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(-n-+1)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(-n+n)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(+ 1n)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(  n +12 3)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(  12 n )', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(+12n-0+1)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(+12N -- 1)', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(+12 N )', ref: box, expect: { throws: true } },
      { match: ':nth-of-type(+ n + 7)', ref: box, expect: { throws: true } },
    ],
  },
  {
    name: ':nth-last-of-type an+b selectors parse',
    // status: 'only',
    markup: `
      <div id="box"></div>
    `,
    cases: [
      { match: ':nth-last-of-type(1n+0)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-of-type(n+0)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-of-type(n)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-of-type(-n+0)', ref: box, expect: { ids: [] } },
      { match: ':nth-last-of-type(-n)', ref: box, expect: { ids: [] } },
      { match: ':nth-last-of-type(N)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-of-type(+n+3)', ref: box, expect: { ids: [] } },
      { match: ':nth-last-of-type( +n + 7 )', ref: box, expect: { ids: [] } },
      { match: ':nth-last-of-type(  N- 123)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-of-type(n- 10)', ref: box, expect: { ids: ['box'] } },
      { match: ':nth-last-of-type(-n\n- 1)', ref: box, expect: { ids: [] } },
      { match: ':nth-last-of-type( 23n\n\n+\n\n123 )', ref: box, expect: { ids: [] } },

      { match: ':nth-last-of-type(n- 1 2)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(n-b1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(n-+1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(n-1n)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(-n -b1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(-1n- b1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(-n-13b1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(-n-+1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(-n+n)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(+ 1n)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(  n +12 3)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(  12 n )', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(+12n-0+1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(+12N -- 1)', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(+12 N )', ref: box, expect: { throws: true } },
      { match: ':nth-last-of-type(+ n + 7)', ref: box, expect: { throws: true } },
    ],
  },
]);
