import { readFileSync } from 'node:fs';
import { runScenarios } from '../../dispatch';

const html = readFileSync(
  'test/selectlet/browser/fixtures/speed/selectors.html',
  'utf8',
);

runScenarios('sizzle', 'normal', [
  {
    name: 'jsdom sizzle benchmark',
    // status: 'only',
    markup: html,
    markupMode: 'html-document',
    timeout: 40_000,
    cases: [
      { select: '.note' },
      { select: '#title' },
      { select: 'h1#title' },
      { select: 'div #title' },
      { select: 'div.example' },
      { select: 'ul .tocline2' },
      { select: '.title' },
      { select: '.toc' },
      { select: '.toc .tocline2' },
      { select: '.tocline2, .tocline3, .tocline4' },
      { select: 'div.example, div.note' },
      { select: 'body' },
      { select: 'div' },
      { select: 'body div' },
      { select: 'div p' },
      { select: 'div > p' },
      { select: 'div + p' },
      { select: 'div ~ p' },
      { select: 'div[class^=exa][class$=mple]' },
      { select: 'div p a' },
      { select: 'div, p, a' },
      { select: 'ul.toc li.tocline2' },
      { select: 'ul.toc > li.tocline2' },
      { select: 'h1#title + div > p' },
      { select: 'h1[id]:contains(Selectors)', expect: { throws: true } },
      { select: 'a[href][lang][class]' },
      { select: 'div[class]' },
      { select: 'div[class=example]' },
      { select: 'div[class^=exa]' },
      { select: 'div[class$=mple]' },
      { select: 'div[class*=e]' },
      { select: 'div[class|=dialog]' },
      { select: 'div[class!=made_up]', expect: { throws: true } },
      { select: 'div[class~=example]' },
      { select: 'div:not(.example)' },
      { select: 'p:contains(selectors)', expect: { throws: true } },
      { select: 'p:nth-child(even)' },
      { select: 'p:nth-child(2n)' },
      { select: 'p:nth-child(odd)' },
      { select: 'p:nth-child(2n+1)' },
      { select: 'p:nth-child(n)' },
      { select: 'p:only-child' },
      { select: 'p:last-child' },
      { select: 'p:first-child' },
      { select: '*' },
      { select: 'A' },
      { select: '[foo]' },
      { select: '[foo="bar"]' },
      { select: '[foo~="bar"]' },
      { select: '[hreflang|="en"]' },
      { select: '[foo^="bar"]' },
      { select: '[foo$="bar"]' },
      { select: '[foo*="bar"]' },
      { select: ':first-child' },
      { select: ':root' },
      { select: ':nth-child(n)' },
      { select: ':nth-last-child(n)' },
      { select: ':nth-of-type(n)' },
      { select: ':nth-last-of-type(n)' },
      { select: ':last-child' },
      { select: ':first-of-type' },
      { select: ':last-of-type' },
      { select: ':only-child' },
      { select: ':only-of-type' },
      { select: ':empty' },
      { select: ':link' },
      { select: ':visited' },
      { select: ':active' },
      { select: ':hover' },
      { select: ':focus' },
      { select: ':lang(fr)' },
      { select: ':target' },
      { select: ':disabled' },
      { select: ':enabled' },
      { select: ':checked' },
      { select: '.warning' },
      { select: '#myid' },
      { select: '#myid' },
      { select: '* B' },
      { select: '* > B' },
      { select: '* + B' },
      { select: '* ~ B' },
      { select: ':not(B)' },
      { select: ':not(*)' },
      { select: ':not([foo])' },
      { select: ':not([foo="bar"])' },
      { select: ':not([foo~="bar"])' },
      { select: ':not([hreflang|="en"])' },
      { select: ':not([foo^="bar"])' },
      { select: ':not([foo$="bar"])' },
      { select: ':not([foo*="bar"])' },
      { select: ':not(:first-child)' },
      { select: ':not(:root)' },
      { select: ':not(:nth-child(n))' },
      { select: ':not(:nth-last-child(n))' },
      { select: ':not(:nth-of-type(n))' },
      { select: ':not(:nth-last-of-type(n))' },
      { select: ':not(:last-child)' },
      { select: ':not(:first-of-type)' },
      { select: ':not(:last-of-type)' },
      { select: ':not(:only-child)' },
      { select: ':not(:only-of-type)' },
      { select: ':not(:empty)' },
      { select: ':not(:link)' },
      { select: ':not(:visited)' },
      { select: ':not(:active)' },
      { select: ':not(:hover)' },
      { select: ':not(:focus)' },
      { select: ':not(:lang(fr))' },
      { select: ':not(:target)' },
      { select: ':not(:disabled)' },
      { select: ':not(:enabled)' },
      { select: ':not(:checked)' },
      { select: ':not(.warning)' },
      { select: ':not(#myid)' },
      { select: 'li,p' },
      { select: 'address' },
      { select: '* ul, p *.t1' },
      { select: '* ul, p *.t1' },
      { select: '#foo p' },
      { select: 'p p[title]' },
      { select: 'address address[title="foo"] span[title="a"]' },
      { select: 'p p[class~="b"] address address[title~="foo"] span[class~="b"]' },
      { select: 'p [title~="hello world"]' },
      { select: 'p p[lang|="en"] address address[lang="fi"] span[lang|="fr"]' },
      { select: 'p p[title^="foo"]' },
      { select: 'p p[title$="bar"]' },
      { select: 'p p[title*="bar"]' },
      { select: 'li .t1 li.t2 .t3' },
      { select: 'p p.t1 p.t2' },
      { select: 'div div.teST div.te div.st div.te.st' },
      { select: 'p .t1.fail .fail.t1 .t2.fail .fail.t2' },
      { select: 'p p.t1.t2 div div.t1 address address.t5.t5' },
      { select: 'p .t1:not(.t2) :not(.t2).t1 .t2:not(.t1) :not(.t1).t2' },
      { select: 'p p:not(.t1):not(.t2) div div:not(.t1) address address:not(.t5):not(.t5)' },
      { select: 'li #t1 li#t2 li#t3 #t4' },
      { select: 'p #test#fail #fail#test #fail div #pass#pass' },
      { select: '.warning div #Aone#Atwo, #Aone#Athree, #Atwo#Athree p #Bone#Btwo, #Bone#Bthree, #Btwo#Bthree #Cone#Ctwo, #Cone#Cthree, #Ctwo#Cthree #Done#Dtwo, #Done#Dthree, #Dtwo#Dthree' },
      { select: 'p.test a p.test *:link' },
      { select: 'p.test a p.test *:visited' },
      { select: 'p:hover a:hover' },
      { select: 'tr:hover td:hover' },
      { select: 'table' },
      { select: 'p' },
      { select: '.a a:hover' },
      { select: '.b a:hover .b a:link' },
      { select: '.c :link .c :visited:hover' },
      { select: 'div:hover > p:first-child' },
      { select: ':link, :visited :link:hover span' },
      { select: 'a:active' },
      { select: 'button:active' },
      { select: 'a:focus' },
      { select: 'p:target' },
      { select: 'p p:target' },
      { select: ':root :target' },
      { select: 'ul > li li:lang(en-GB)' },
      { select: 'button input button:enabled input:enabled' },
      { select: 'button input button:disabled input:disabled' },
      { select: 'input, span input:checked, input:checked + span' },
      { select: 'html *:root' },
      { select: ':root:first-child :root:last-child :root:only-child :root:nth-child(1) :root:nth-child(n) :root:nth-last-child(1) :root:nth-last-child(n) :root:first-of-type :root:last-of-type :root:only-of-type :root:nth-of-type(1) :root:nth-of-type(n) :root:nth-last-of-type(1) :root:nth-last-of-type(n) p' },
      { select: '* html * :root p' },
      { select: '.red ul > li:nth-child(odd) ol > li:nth-child(even) table.t1 tr:nth-child(-n+4) table.t2 td:nth-child(3n+1)' },
      { select: '.green ul > li:nth-child(odd) ol > li:nth-child(even) table.t1 tr:nth-child(-n+4) table.t2 td:nth-child(3n+1)' },
      { select: '.red ul > li:nth-last-child(odd) ol > li:nth-last-child(even) table.t1 tr:nth-last-child(-n+4) table.t2 td:nth-last-child(3n+1)' },
      { select: '.green ul > li:nth-last-child(odd) ol > li:nth-last-child(even) table.t1 tr:nth-last-child(-n+4) table.t2 td:nth-last-child(3n+1)' },
      { select: '.red p:nth-of-type(3) dl > :nth-of-type(3n+1)' },
      { select: '.red p:nth-last-of-type(3) dl > :nth-last-of-type(3n+1)' },
      { select: '.red .t1 td:first-child p > *:first-child' },
      { select: '.red .t1 td:last-child p > *:last-child' },
      { select: '.red address address:first-of-type' },
      { select: '.red address address:last-of-type' },
      { select: '.red p:only-child div.testText > div > p' },
      { select: '.red .t1 :only-of-type' },
      { select: '.white .red div.t1 p' },
      { select: '.white .green div.t1 p' },
      { select: '.white .red div > p.test' },
      { select: '.white .green div > p.test' },
      { select: '.fail > div   .control' },
      { select: '#fail > div   p' },
      { select: '.red div.stub > p + p' },
      { select: '.green .white div.stub > p + p' },
      { select: '.fail + div   .control' },
      { select: '.red div.stub > p ~ p' },
      { select: '.green div.stub > p ~ p' },
      { select: 'div.stub > * div.stub *:not(.foo)' },
      { select: 'div.stub > * div.stub *:not(#foo)' },
      { select: 'div.stub > * div.stub *:not(:link)' },
      { select: 'div.stub > * div.stub *:not(:visited)' },
      { select: 'div.stub * div.stub > * > *:not(:hover)' },
      { select: 'div.stub * div.stub > * > *:not(:active)' },
      { select: 'a:not(:focus) a' },
      { select: 'p p:not(:target)' },
      { select: 'p p:not(:target)' },
      { select: 'div.stub * div.stub *:not(:lang(fr)) ' },
      { select: 'button input button:not(:enabled) input:not(:enabled)  ' },
      { select: 'button input button:not(:disabled) input:not(:disabled) ' },
      { select: 'input, span input:not(:checked), input:not(:checked) + span ' },
      { select: 'p:not(:root) div * ' },
      { select: 'html:not(:root), test:not(:root) p ' },
      { select: '.red ul > li:not(:nth-child(odd)) ol > li:not(:nth-child(even)) table.t1 tr:not(:nth-child(-n+4)) table.t2 td:not(:nth-child(3n+1)) table.t1 td, table.t2 td ' },
      { select: '.green ul > li:not(:nth-child(odd)) ol > li:not(:nth-child(even)) table.t1 tr:not(:nth-child(-n+4)) table.t2 td:not(:nth-child(3n+1)) table.t1 td, table.t2 td ' },
      { select: '.red ul > li:not(:nth-last-child(odd)) ol > li:not(:nth-last-child(even)) table.t1 tr:not(:nth-last-child(-n+4)) table.t2 td:not(:nth-last-child(3n+1)) table.t1 td, table.t2 td ' },
      { select: '.green ul > li:not(:nth-last-child(odd)) ol > li:not(:nth-last-child(even)) table.t1 tr:not(:nth-last-child(-n+4)) table.t2 td:not(:nth-last-child(3n+1)) table.t1 td, table.t2 td ' },
      { select: '.red p:not(:nth-of-type(3)) dl > *:not(:nth-of-type(3n+1)) ' },
      { select: '.green p:not(:nth-of-type(3)) dl > *:not(:nth-of-type(3n+1)) ' },
      { select: '.red p:not(:nth-last-of-type(3)) dl > *:not(:nth-last-of-type(3n+1)) ' },
      { select: '.green p:not(:nth-last-of-type(3)) dl > *:not(:nth-last-of-type(3n+1)) ' },
      { select: '.red .t1 td:not(:first-child) p > *:not(:first-child) table.t1 td ' },
      { select: '.green .t1 td:not(:first-child) p > *:not(:first-child) table.t1 td ' },
      { select: '.red .t1 td:not(:last-child) p > *:not(:last-child) table.t1 td ' },
      { select: '.green .t1 td:not(:last-child) p > *:not(:last-child) table.t1 td ' },
      { select: '.red address address:not(:first-of-type) ' },
      { select: '.red address address:not(:last-of-type) ' },
      { select: '.red p:not(:only-child) div.testText > div > p ' },
      { select: '.green p:not(:only-child) div.testText > div > p ' },
      { select: '.red .t1 *:not(:only-of-type) ' },
      { select: '.green .t1 *:not(:only-of-type) ' },
      { select: 'p p:not(:not(p)) ' },
      { select: 'p blockquote > div p ' },
      { select: 'p blockquote + div ~ p ' },
      { select: 'p blockquote + div ~ p ' },
      { select: 'p blockquote + div p ' },
      { select: 'p blockquote + div p ' },
      { select: 'p blockquote div > p ' },
      { select: 'p blockquote ~ div + p ' },
      { select: 'p blockquote ~ div + p ' },
      { select: 'div :not(:enabled):not(:disabled) p ' },
      { select: 'line   [type~=odd]   line:nth-of-type(odd)   [hidden] ' },
      { select: 'line   [type~=odd]   line:nth-of-type(odd)   [hidden] ' },
      { select: 'line   [type~=match]   line:nth-child(3n-1)   [hidden] ' },
      { select: 'line   [type~=match]   line:nth-child(3n-1)   [hidden] ' },
      { select: 'line   [type~=match]   line:nth-last-of-type(3n-1)   [hidden] ' },
      { select: 'line   [type~=match]   line:nth-last-of-type(3n-1)   [hidden] ' },
      { select: 'p  p:empty ' },
      { select: 'address:empty  address  .text ' },
      { select: 'address:empty  address  .text ' },
      { select: 'address:empty  address  .text ' },
      { select: 'address  address:empty  .text ' },
      { select: 'address  address:empty  .text ' },
      { select: 'address  address:empty  .text ' },
      { select: 'p   p, ', expect: { throws: true } },
      { select: 'p   .5cm ', expect: { throws: true } },
      { select: 'p   .\\5cm ' },
      { select: 'p   .two\\ words ' },
      { select: 'p   .one.word ' },
      { select: '.one\\.word   p ' },
      { select: 'p   foo & address, p ' },
      { select: 'foo & address, p   p ' },
      { select: 'foo & address, p   p ' },
      { select: 'p   [*=test] ', expect: { throws: true } },
      { select: 'p   p:subject', expect: { throws: true } },
      { select: 'p   p   *   p > *   p + *   p ~ * ' },
      { select: 'td > div   td > div > span ' },
      { select: '   .test strong ' },
      { select: 'p  .fail ' },
      { select: 'p  .13 ', expect: { throws: true } },
      { select: 'p  .\\13 ' },
      { select: 'p  .\\31 \\33 ' },
      { select: 'div  p::first-child ', expect: { throws: true } },
      { select: '.cs  .cs P  .cs .a  .cs .span1 span  .cs .span2  .cs .span2 SPAN  .cs .span2 span  .ci  .ci P  .ci .a  .ci .span1 span  .ci .span2 SPAN ' },
      { select: 'p foo\\:bar ' },
      { select: 'p ..test .foo..quux .bar. ', expect: { throws: true } },
      { select: '#test    #test:not(:empty) ' },
      { select: '#test1    #test1:empty    #test2    #test2:empty ' },
      { select: '#test    #stub ~ div div + div > div ' },
      { select: '[test]    stub ~ [|attribute^=start]:not([|attribute~=mid])[|attribute*=dle][|attribute$=end] ~ t ' },
      { select: '#two:first-child    #three:last-child ' },
      { select: 'input, span  input:indeterminate, input:indeterminate + span ' },
      { select: 'input, span  input:checked, input:checked + span ' },
      { select: 'input, span  input:not(:checked), input:not(:checked) + span ' },
      { select: 'p[example=publicclass]' },
      { select: 'p[example="public"]' },
    ],
  },
]);
